sequences_array = [{:sequence_comp => "AGCCTTTGACATCCTAGGACGACTTCTGGAGACAGATTTCTTCCCTTCGGGGACCTAGTGAC"},
{:sequence_comp => "TGGTCTTGACATAGTAAGAACTTTCCAGAGATGGATTGGTGCCTTCGGGAACTTACATAC"},
{:sequence_comp => "TGGCCTTGACATGCAGAGAACTTTCCAGAGATGGATTGGTGCCTTCGGGAACTCTGACAC"},
{:sequence_comp => "AGGTCTTGACATCCCAGTGACCGTCCTAGAGATAGGATTTTTCTTCGGAACACTGGAGAC"},
{:sequence_comp => "TACTCTTGACATCCAGAGAACTTAGCAGAGATGCTTTGGTGCCTTCGGGAACTCTGAGAC"}]
@sequences = Array.new
sequences_array.each do |seq|
   @sequences.push(FactoryGirl.create(:sequence, sequence_comp: seq[:sequence_comp]))
end
